### ISSUE TITLE
Wrong lead delete URL in REST API docs

### ISSUE THREAD

**Issue by cedel1** [mautic/developer-documentation#11]
The docs state (excerpt below) that lead delete URL for REST API is /leads/{id}, which is incorrect (and very confusing).

`HTTP Request
DELETE /leads/ID`

The correct URL for REST API seems to be `DELETE /leads/ID/delete`.

**Comment by cedel1** [comment]
Just added a pull request https://github.com/mautic/developer-documentation/pull/12 with correction.

**Comment by alanhartless** [comment]
Thanks for PRing this!
