### ISSUE TITLE
batch contact creation/edition non documented

### ISSUE THREAD

**Issue by npracht** [mautic/developer-documentation#116]
# Description
It seems that an API route is existing to create or edit contact (maybe delete?) contacts by batches.
I found it mentioned here https://github.com/mautic/mautic/issues/6210 and here https://github.com/mautic/mautic/pull/5979.

Nothing exists in the documentation about it: https://developer.mautic.org/#rest-api

@alanhartless could you write those few lines of doc please 🙏 
Thanks a lot !!

**Comment by StoppingBuck** [comment]
It seems that batch delete contacts is available, but hidden in the code. 
After digging around a bit, I've found what seems to be it here: https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Controller/LeadController.php#L1077

If I can decipher what's going on there, I might be able to write a few lines about how it works.

As for batch adding and editing contacts, I already know how to do that. @npracht here are a few lines, if you want to add them to the documentation (or I could create a PR myself if I could find the place):

----

**Batch add contacts:**
POST /contacts/batch/new
with a JSON body consisting of an array of objects with the desired data, like this:

```
[
	{
		"firstname": "Test",
		"lastname": "Testname1",
		"email": "test1@test.dk"
	},
	{	
		"firstname": "Test",
		"lastname": "Testname2",
		"email": "test2@test.dk"
	}
]
```

----
**Batch edit contacts:**
PATCH /contacts/batch/edit
with a JSON body consisting of an array of objects with the id (required) and the fields to change. In the below example, the contact with id 346435 will get their lastname changed to 'Testname' while the contact with id 94150 will get the tag 'recent donation' removed (if it exists) and get the tag 'expired' added:

```
[
	{
		"id": "346435",
		"lastname": "Testname"
	},
	{
		"id": "94150",
		"tags": "-recent donator, expired"
	}
]
```

**Comment by PierreAmmeloot** [comment]
@escopecz can you update Mautic developper guide with batch information?

**Comment by StoppingBuck** [comment]
There is apparently also an undocumented possibility to batch add people to DNC: https://github.com/mautic/mautic/blob/4368fac19827a7aa08fac2f47f64070835c7a5e9/app/bundles/LeadBundle/Controller/LeadController.php#L1580

**Comment by kamikazebr** [comment]
WOW! @StoppingBuck  TYVM! We need document it! Very useful!

**Comment by zentavr** [comment]
I wonder if there is any mentions about that in https://github.com/mautic/api-library?

**Comment by zentavr** [comment]
> I wonder if there is any mentions about that in https://github.com/mautic/api-library?
replying to my own question above:

Yes, api-library 2.16.1 do have batch methods as well, i.e.:
```php
$contact = $contactApi->createBatch($batchData);
```
Just `grep Batch lib/Api/Api.php`:
```php
    public function createBatch(array $parameters)
    public function editBatch(array $parameters, $createIfNotExists = false)
    public function deleteBatch(array $ids)
```

**Comment by StoppingBuck** [comment]
@RCheesley Can you assign this to me? It seems like a good first task to get into the whole PR routine and I've basically already made a draft above anyway :smiley_cat:

**Comment by RCheesley** [comment]
Absolutely!

**Comment by Ziedpad** [comment]
it is possible to change the Label of the standard Field in Mautic from API ?
I have Version 3.0.1
// Get contact field context:
$fieldApi = $api->newApi("contactFields", $auth, $apiUrl);
$id = 1;
$data = array(
'label' => 'API test field',
'type' => 'text',
);

// Create new a field of ID 1 is not found?
$createIfNotFound = true;

$result = $fieldApi->edit($id, $data, $createIfNotFound);

I have a 500 type error. "message":"Looks like I encountered an error (error slatedocs#500)

**Comment by ke-np** [comment]
@escopecz Hi John, Could you please help to confirm that these batch APIs are good for production usage? I'm not able to find its official documentation so just want to double-check. Thank you!

**Comment by escopecz** [comment]
Yes, we use them in production :+1:

**Comment by dennisameling** [comment]
Batch delete documentation has been added in https://github.com/mautic/developer-documentation/pull/177

**Comment by dennisameling** [comment]
Just merged the following 3 PRs which add several docs for batch operations:

- batch delete #177
- batch edit - #176
- batch new - #130

We can close this issue now 👍🏼
