### ISSUE TITLE
An exception occurred while executing 'UPDATE lead_event_log

### ISSUE THREAD

**Issue by GenericUK** [mautic/developer-documentation#129]
I wrote a plugin that updates an existing contact. After upgrading to the latest version of Mautic my plugin now fails with the following error.

An exception occurred while executing 'UPDATE lead_event_log SET lead_id = 0 WHERE lead_id = 96':

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mautic_db`.`lead_event_log`, CONSTRAINT `FK_753AF2E55458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE)

**Comment by escopecz** [comment]
Why did you choose the documentation repository to report this? Why do you set the lead_id as 0? Set it as null.

**Comment by GenericUK** [comment]
Sorry, didn't mean to choose this repository, I was using mobile. Happy to move it if you think it's worth investigating. I am using lead_id as null and it's been working for 2 years until recent update.

**Comment by escopecz** [comment]
Try to find out where it's converting null to 0 then.
