### ISSUE TITLE
Documenting contact tags removal 

### ISSUE THREAD

**Issue by nikolanedic** [mautic/developer-documentation#131]
It would be nice if feature for removing tags from contact via API by adding `-` before a tag in PUT request was documented. I'm willing to do it, but I would like to here some suggestions on where exactly that should be added.

**Comment by escopecz** [comment]
I think it belongs here: https://github.com/mautic/developer-documentation/blob/master/source/includes/_api_endpoint_contacts.md

**Comment by escopecz** [comment]
Added in https://github.com/mautic/developer-documentation/pull/132
