### ISSUE TITLE
Mispelled file on theme structure

### ISSUE THREAD

**Issue by npracht** [mautic/developer-documentation#14]
Hi, i think .phpp extension written here is mispelled.
https://developer.mautic.org/#theme-directory-structure

I dunno how to contribute editing a Slate file. I'll let you manage.

Best,

N.

**Comment by escopecz** [comment]
Thanks for pointing it out. It's basically the same as contributing to the Mautic docs

https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by alanhartless** [comment]
Fixed.
