### ISSUE TITLE
Example custom event does not extend Symfony Event

### ISSUE THREAD

**Issue by RaphaelWoude** [mautic/developer-documentation#146]
Docs: https://developer.mautic.org/#custom-events

The docs mention that the event should extend `Symfony\Component\EventDispatcher\Event`, but the code example right next to it doesn't extend anything. Please update the code example.

![image](https://user-images.githubusercontent.com/47354694/78137262-4f397900-7425-11ea-8354-12c3bbaf4902.png)

**Comment by RCheesley** [comment]
Thanks for flagging this @RaphaelWoude, are you in a position to make a PR to include a code sample at all? If so it would be much appreciated!

I believe this is the file that needs updating: https://github.com/mautic/developer-documentation/blob/master/source/includes/_plugin_misc_events.md

**Comment by RaphaelWoude** [comment]
Yes. I can make a pull request to fix the sample code.
Here is the pull request: https://github.com/mautic/developer-documentation/pull/148
