### ISSUE TITLE
No refresh token expiry date

### ISSUE THREAD

**Issue by aurelianpop** [mautic/developer-documentation#15]
Hello, is there any way of getting the Refresh token expiry date ? i need that date to remind the user to reauthorize

**Comment by alanhartless** [comment]
Hi!

When you perform the oauth 2 process, the refresh token expiry will be returned with the access token. Add that to the current time and it'll give you the refresh token expiration date/time.

Thanks,
Alan

**Comment by ced-mohitp** [comment]
Hi @alanhartless 

I don't think that's the exirpy time of refresh token. It's the expiry time of access token. 
Is there any way by which we can get the expiry time of refresh token and get the exact time of when we need to reauth again.
