### ISSUE TITLE
Typo at writting plugin docs

### ISSUE THREAD

**Issue by dhilst** [mautic/developer-documentation#154]
There is something that looks a lot like a typo at docs

<img width="387" alt="image" src="https://user-images.githubusercontent.com/392820/83055655-80e84e00-a02a-11ea-843a-857704842e36.png">

I search for `CHANGE CHANGE` in github search but can't  find the document with the typo, I willing to create a PR for it. 

Regards

**Comment by RCheesley** [comment]
Ahh that makes sense, the developer documentation is a separate repository. I have transferred this issue over to the dev docs.

Take a look at the code - you should be able to find where this is, and make a pull request to fix it.

Thanks so much for taking the time to report it, and for offering to fix it!

**Comment by dhilst** [comment]
@RCheesley Thanks, I open a pull request!

**Comment by RCheesley** [comment]
@dhilst thanks for making the PR - much appreciated! If you spot anything else do please feel free to submit any changes!
