### ISSUE TITLE
No contact batch endpoint information

### ISSUE THREAD

**Issue by tomekkowalczyk** [mautic/developer-documentation#174]
We have an undocumented Lead endpoint API that is public and tested
1. `PUT /api/contacts/batch/edit` - https://developer.mautic.org/#edit-contact
2. `POST /api/contacts/batch/new` - https://developer.mautic.org/#create-contact

**Comment by tomekkowalczyk** [comment]
I added PR
1. batch delete https://github.com/mautic/developer-documentation/pull/177
2. batch edit - https://github.com/mautic/developer-documentation/pull/176
3. batch new - @PierreAmmeloot https://github.com/mautic/developer-documentation/pull/130

**Comment by dennisameling** [comment]
Thanks for reporting this and providing the PRs @tomekkowalczyk and @PierreAmmeloot! All PRs have now been merged and will go live today, so I'm closing this PR.
