### ISSUE TITLE
parameters missing about list_contacts route in documentation

### ISSUE THREAD

**Issue by npracht** [mautic/developer-documentation#215]
# Description
We found API supports `include` parameter (not documented).
Very useful, you can choose fields to process in response with array parameter `select[]` of field aliases. `id` is required.

For example you can do `select[]=firstname&select[]=email&select[]=id`

`https://your-mautic.tld/api/contacts?select[]=firstname&select[]=email&select[]=id&search=segment%3Asegment_alias&limit=50&start=2770`

Request is much faster depending on the values you store and the amount of custom fields you have.

**Comment by RCheesley** [comment]
Have you checked in the new developer documentation repo? Everything is overhauled and it might already be documented there?

**Comment by RCheesley** [comment]
Please raise in the new repo so that it can be actioned there!
