### ISSUE TITLE
developer.mautic.org show deprecated way to send email to contact along with wrong HTTP verb

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/developer-documentation#59]
[This section of the documentation](https://developer.mautic.org/#send-email-to-contact) shows the deprecated way to send emails to contact along with the wrong HTTP verb

## On the website:
<h3 id="send-email-to-contact">Send Email to Contact</h3>
<p>Send a predefined email to existing contact.</p>
<h4 id="http-request">HTTP Request</h4>
<p><code class="prettyprint">DELETE /emails/ID/send/contact/CONTACT_ID</code></p>
<h4 id="response">Response</h4>
<p><code class="prettyprint">Expected Response Code: 200</code></p>
<p><strong>Properties</strong>
<code class="prettyprint">json
{
    &quot;success&quot;: 1
}
</code></p>

## In Mautic's configuration:
```php
'mautic_api_sendcontactemail' => [
    'path'       => '/emails/{id}/contact/{leadId}/send',
    'controller' => 'MauticEmailBundle:Api\EmailApi:sendLead',
    'method'     => 'POST',
],
```

**Comment by escopecz** [comment]
Isn't it fixed here?: https://github.com/mautic/developer-documentation/pull/56

**Comment by MaxWebmecanik** [comment]
@escopecz Seems like that pull request _would_ fix it.
How long does it take for PRs on this repo to end up on developer.mautic.org?

**Comment by escopecz** [comment]
It depends on how fast they can be reviewed. The community can help a lot with it. I take this issue as successful review of the linked PR.
