### ISSUE TITLE
Typo: dynamicConent/Dynamic Conent (missing t)

### ISSUE THREAD

**Issue by pietervanleuven** [mautic/developer-documentation#62]
In this file: https://github.com/mautic/developer-documentation/blob/master/source/includes/_api_endpoint_dynamic_contents.md

Looks like it's introduced with this commit: https://github.com/mautic/developer-documentation/commit/237f26bd14fefb5081ccc5d32704cfcf66ca0fc8

**Comment by escopecz** [comment]
Thanks for pointing that out. Fixed in https://github.com/mautic/developer-documentation/pull/63
