### ISSUE TITLE
Incorrect Endpoint for the List Webhooks method

### ISSUE THREAD

**Issue by sambarnes90** [mautic/developer-documentation#96]
The ["List Webhooks" method](https://github.com/mautic/developer-documentation/blob/master/source/includes/_api_endpoint_webhooks.md#list-webhooks) suggests that the endpoint is as follows:

`GET /webhooks`

From my testing it appears that the endpoint for this method is consistent with all the other Webhook methods, and should be:

`GET /hooks`

Unless I'm doing something very very wrong...

**Comment by escopecz** [comment]
you are right. Are you able to send a pull request with the fix?

**Comment by sambarnes90** [comment]
Hopefuly I've done that correctly?

Not actually created a pull request before...

**Comment by escopecz** [comment]
Yes, perfect!
